name: Documentation Issue
description: Report issues with documentation (errors, unclear instructions, missing info, etc.)
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help improve our documentation!
        
        **Note:** This template is for documentation issues only. For code bugs or feature requests, please use the appropriate template.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Incorrect or outdated information
        - Unclear or confusing explanation
        - Missing documentation
        - Broken link or image
        - Typo or grammatical error
        - Code example doesn't work
        - Other
    validations:
      required: true

  - type: input
    id: doc-url
    attributes:
      label: Documentation URL (if applicable)
      description: Link to the specific page or section with the issue. Leave blank if requesting new documentation.
      placeholder: "https://openaq.github.io/openaq-r/... or leave blank for missing documentation"
    validations:
      required: false

  - type: textarea
    id: issue-description
    attributes:
      label: Describe the Issue
      description: What's wrong with the current documentation?
      placeholder: "The current documentation states X, but this is incorrect because..."
    validations:
      required: true

  - type: textarea
    id: expected-content
    attributes:
      label: Suggested Improvement
      description: How could the documentation be improved? What should it say instead?
      placeholder: "The documentation should explain that..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information (screenshots, related docs, etc.)
      placeholder: "I was trying to accomplish X when I found this issue..."
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to help fix this documentation issue?
      options:
        - label: I'm willing to submit a PR to fix this documentation issue
          required: false