# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
    push:
      branches: [main]
    pull_request:

name: check.yaml

permissions: read-all

jobs:
    R-CMD-check:
      if: "!contains(github.event.head_commit.message, 'check skip')"
      runs-on: ${{ matrix.config.os }}

      name: ${{ matrix.config.os }} (${{ matrix.config.r }})

      strategy:
        fail-fast: false
        matrix:
          config:
            - {os: macos-latest,   r: 'release'}

            - {os: windows-latest, r: 'release'}
            # use 4.0 or 4.1 to check with rtools40's older compiler
            - {os: windows-latest, r: 'oldrel-1'}
            - {os: windows-latest, r: 'oldrel-2'}

            - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release'}
            - {os: ubuntu-latest,  r: 'release'}
            - {os: ubuntu-latest,  r: 'oldrel-1'}
            - {os: ubuntu-latest,  r: 'oldrel-2'}
            - {os: ubuntu-latest,  r: 'oldrel-3'}
            #- {os: ubuntu-latest,  r: 'oldrel-4'}

      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        R_KEEP_PKG_SOURCE: yes

      steps:
        - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

        - uses: r-lib/actions/setup-pandoc@d3c5be51b12e724e68f33216ca3c148b66d5f0b6

        - uses: r-lib/actions/setup-r@d3c5be51b12e724e68f33216ca3c148b66d5f0b6
          with:
            r-version: ${{ matrix.config.r }}
            http-user-agent: ${{ matrix.config.http-user-agent }}
            use-public-rspm: true

        - uses: r-lib/actions/setup-r-dependencies@d3c5be51b12e724e68f33216ca3c148b66d5f0b6
          with:
            extra-packages: any::rcmdcheck
            needs: check

        - uses: r-lib/actions/check-r-package@d3c5be51b12e724e68f33216ca3c148b66d5f0b6
          with:
            upload-snapshots: true
            build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
